name: python-publish
on: [push]
jobs:
  Publish-To-PYPI:
    runs-on: ubuntu-latest
    steps:
      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
